In [13]:
!pip install pandas numpy openpyxl streamlit

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in .\.venv\Lib\site-packages (2.4.5)
Requirement already satisfied: openpyxl in .\.venv\Lib\site-packages (3.1.5)
Requirement already satisfied: streamlit in .\.venv\Lib\site-packages (1.57.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in .\.venv\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in .\.venv\Lib\site-packages (from streamlit) (6.1.0)
Requirement already satisfied: blinker<2,>=1.5.0 in .\.venv\Lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in .\.venv\Lib\site-packages (from streamlit) (7.1.2)
Requirement already satisfied: click<9,>=7.0 in .\.venv\Lib\site-packages (from streamlit) (8.4.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in .\.venv\Lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: packaging>=20 in .\.venv\Lib\site-packages (from streamlit) (26.2)
Requirement already satisfied: pillow<13,>=7.1.0 in .\.venv\Lib\site-packages (from streamlit) (12.2.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in .\.venv\Lib\site-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in .\.venv\Lib\site-packages (from streamlit) (7.34.1)
Requirement already satisfied: pyarrow>=7.0 in .\.venv\Lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in .\.venv\Lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in .\.venv\Lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in .\.venv\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in .\.venv\Lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in .\.venv\Lib\site-packages (from streamlit) (1.0.0)
Requirement already satisfied: uvicorn>=0.30.0 in .\.venv\Lib\site-packages (from streamlit) (0.47.0)
Requirement already satisfied: httptools>=0.6.3 in .\.venv\Lib\site-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in .\.venv\Lib\site-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in .\.venv\Lib\site-packages (from streamlit) (0.0.29)
Requirement already satisfied: websockets>=12.0.0 in .\.venv\Lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in .\.venv\Lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in .\.venv\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in .\.venv\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in .\.venv\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in .\.venv\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.21.2)
Requirement already satisfied: colorama in .\.venv\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in .\.venv\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in .\.venv\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.venv\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\.venv\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in .\.venv\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\.venv\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.4.22)
Requirement already satisfied: MarkupSafe>=2.0 in .\.venv\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in .\.venv\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in .\.venv\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in .\.venv\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in .\.venv\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: h11>=0.8 in .\.venv\Lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)

In [14]:
import sys
print(sys.executable)

c:\Users\dell\OneDrive\Desktop\myfirstproject\.venv\Scripts\python.exe

In [15]:
import numpy as np 
import pandas as pd

In [16]:
df = pd.read_csv('online_retail.csv')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [17]:
df[['Quantity','UnitPrice']].describe()

            Quantity      UnitPrice
count  541909.000000  541909.000000
mean        9.552250       4.611114
std       218.081158      96.759853
min    -80995.000000  -11062.060000
25%         1.000000       1.250000
50%         3.000000       2.080000
75%        10.000000       4.130000
max     80995.000000   38970.000000

In [18]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [19]:
#We are going to fill the missing with "99999" 
df['CustomerID']=df['CustomerID'].fillna(99999)
print("Remaining missing values is CUstomerID=",df['CustomerID'].isnull().sum())

Remaining missing values is CUstomerID= 0

In [20]:
df['Description'] = df['Description'].fillna("Unknown Item")
print("The remaining missing values in Description is =", df['Description'].isnull().sum())

The remaining missing values in Description is = 0

In [21]:
df[['Quantity','UnitPrice']].describe()

            Quantity      UnitPrice
count  541909.000000  541909.000000
mean        9.552250       4.611114
std       218.081158      96.759853
min    -80995.000000  -11062.060000
25%         1.000000       1.250000
50%         3.000000       2.080000
75%        10.000000       4.130000
max     80995.000000   38970.000000

In [22]:
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]
df[['Quantity','UnitPrice']].describe()

            Quantity      UnitPrice
count  530104.000000  530104.000000
mean       10.542037       3.907625
std       155.524124      35.915681
min         1.000000       0.001000
25%         1.000000       1.250000
50%         3.000000       2.080000
75%        10.000000       4.130000
max     80995.000000   13541.330000